version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/app/dist
    command: bun run build  # Build the Vue.js app with Bun

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # FastAPI runs on port 8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:1.25.3
    ports:
      - "81:81"  # Nginx listens on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html  # Mount Vue.js static files
    depends_on:
      - backend

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: squirrel_sums_cloudflare_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiZmU2YzA2NWM4MmI5NTNhOGQ5ZWM2NTNkMWQ2YjIzMjAiLCJ0IjoiN2JhYzhlMDEtMDQyZi00ODZhLWFhYjYtYjU1N2JiNzQ2ZjkxIiwicyI6IlpEQTNaak14WXpVdE5URTVOeTAwTVRJeUxXRTVPR0l0T1dGbU1tVXdPRFJoTVdabSJ9
